[package]
name = "alpaca-extfs"
version = "0.2.0"
edition = "2021"
license = "MIT"



[dependencies]
fuser = "0.15"
libc = "0.2"
nix = { version = "0.29", features = ["fs", "mount"] }
clap = { version = "4.5", features = ["derive"] }

[build-dependencies]
cc = "1.2"
bindgen = "0.71"
pkg-config = "0.3"

